services:
  api:
    build:
      context: apps/api
    ports:
      - 3000:3000
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    init: true
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: apps/worker
    volumes:
      - ./apps/worker:/app
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s