services:
  workspace:
    image: node:26
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity
  api:
    build:
      context: apps/api
    ports:
      - 3000:3000
    volumes:
      - ./apps/api:/app
      - /app/node_modules
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672