name: CI

on:
  push:
    branches:
      - '*'

jobs:
  tests-and-docs:
    name: Tests and docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Warmup the Docker Compose stack
        run: docker compose up -d --wait

      - name: Run API test suite
        background: true
        run: docker compose run --rm api npm test
      
      - name: Run API E2E test suite
        background: true
        run: docker compose run --rm api npm run test:e2e
      
      - name: Run API linting
        background: true
        run: docker compose run --rm api npm run lint
      
      - name: Run Worker test suite
        background: true
        run: docker compose exec worker uv run python -m pytest

      - name: Wait for tests
        wait-all:
      
      - name: Fetch Swagger JSON
        run: curl -o swagger.json http://localhost:3000/docs-json

      - name: Build Swagger UI static site
        uses: Legion2/swagger-ui-action@v1.3.0
        with:
          spec-file: swagger.json
          output: swagger-ui
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: swagger-ui

      - name: Tear down Docker Compose
        if: always()
        run: docker compose down --remove-orphans

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    needs: tests-and-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/master'