name: CI

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Warmup the Docker Compose stack
        run: docker compose up -d --wait

      - name: Run API test suite
        background: true
        run: docker compose run --rm api npm test
      
      - name: Run API E2E test suite
        background: true
        run: docker compose run --rm api npm run test:e2e
      
      - name: Run API linting
        background: true
        run: docker compose run --rm api npm run lint
      
      - name: Run Worker test suite
        background: true
        run: docker compose exec worker uv run python -m pytest

      - name: Wait for tests
        wait-all:
      
      - name: Generate Swagger documentation
        run: curl -o swagger.json http://localhost:3000/docs-json
      
      - name: Build Swagger UI static site
        uses: peter-evans/swagger-github-pages@v2
        with:
          spec-file: swagger.json
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swagger-ui

      - name: Tear down Docker Compose
        if: always()
        run: docker compose down --remove-orphans
